### ISSUE TITLE
 I have some errors in the implemention.

### ISSUE THREAD

**Issue by Crownwzt** [CrickWu/Clevr-for-StoryGAN#1]
In your recent contribution--the vec_generation, your want to change feature dimensions exacted, but the return feature list is a 13 dimensions vector not an 18-dimensional vector, how to assign img_feature?

**Comment by CrickWu** [comment]
Thanks for raising this question. We have fixed this problem. Actually, in this repo, we originally used RGB encoding for the object colors which is incompatible with the 1-hot encoding way our paper has used. You should be able to reproduce the same dimension feature now.
